project:
  name: Ozon Code Platform Business Equipment Request API
  debug: true
  environment: development
  serviceName: bss_equipment_request_service

telemetry:
  graylogPath: 127.0.0.1:12201

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  service: "bss-equipment-request-api"
  host: "jaeger"
  port: ":6831"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: bss_equipment_request_api
  sslmode: disable
  migrations: migrations
  driver: pgx
  connectAttempts: 15
