project:
  name: Ozon Code Platform Template API
  debug: true
  environment: development
  serviceName: bss_equipment_request_retranslator

telemetry:
  graylogPath: 127.0.0.1:12201

retranslator:
  channelSize: 512
  consumerCount: 2
  consumeSize: 10
  consumeTimeout: 1s
  producerCount: 28
  producerTimeout: 1s
  workerCount:   2
  batchSize: 20

metrics:
  host: 0.0.0.0
  port: 9103
  path: /metrics

jaeger:
  service: "bss-equipment-request-api_retranslator"
  host: "jaeger"
  port: ":6831"

status:
  host: 0.0.0.0
  port: 8300
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: bss_equipment_request_api
  sslmode: disable
  migrations: migrations
  driver: pgx

kafka:
  capacity: 512
  topic: "bss-equipment-request-events-retranslator"
  groupId: "bss-equipment-request-retranslator"
  brokers:
    - "kafka:9092"
    - "localhost:9094"
