# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/bss_equipment_request_api/v1/bss_equipment_request_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCozonmp/bss_equipment_request_api/v1/bss_equipment_request_api.proto\x12#ozonmp.bss_equipment_request_api.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n\x10\x45quipmentRequest\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x1e\n\nemployeeId\x18\x02 \x01(\x04R\nemployeeId\x12 \n\x0b\x65quipmentId\x18\x03 \x01(\x04R\x0b\x65quipmentId\x12\x38\n\tcreatedAt\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x32\n\x06\x64oneAt\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x06\x64oneAt\x12:\n\x18\x65quipmentRequestStatusId\x18\x06 \x01(\x04R\x18\x65quipmentRequestStatusId\"<\n!DescribeEquipmentRequestV1Request\x12\x17\n\x02id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\x02id\"s\n\"DescribeEquipmentRequestV1Response\x12M\n\x06result\x18\x01 \x01(\x0b\x32\x35.ozonmp.bss_equipment_request_api.v1.EquipmentRequestR\x06result2\xf7\x01\n\x1d\x42ssEquipmentRequestApiService\x12\xd5\x01\n\x1a\x44\x65scribeEquipmentRequestV1\x12\x46.ozonmp.bss_equipment_request_api.v1.DescribeEquipmentRequestV1Request\x1aG.ozonmp.bss_equipment_request_api.v1.DescribeEquipmentRequestV1Response\"&\x82\xd3\xe4\x93\x02 \"\x1b/v1/equipment_requests/{id}:\x01*BeZcgithub.com/ozonmp/bss-equipment-request-api/pkg/bss-equipment-request-api;bss_equipment_request_apib\x06proto3')



_EQUIPMENTREQUEST = DESCRIPTOR.message_types_by_name['EquipmentRequest']
_DESCRIBEEQUIPMENTREQUESTV1REQUEST = DESCRIPTOR.message_types_by_name['DescribeEquipmentRequestV1Request']
_DESCRIBEEQUIPMENTREQUESTV1RESPONSE = DESCRIPTOR.message_types_by_name['DescribeEquipmentRequestV1Response']
EquipmentRequest = _reflection.GeneratedProtocolMessageType('EquipmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _EQUIPMENTREQUEST,
  '__module__' : 'ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_equipment_request_api.v1.EquipmentRequest)
  })
_sym_db.RegisterMessage(EquipmentRequest)

DescribeEquipmentRequestV1Request = _reflection.GeneratedProtocolMessageType('DescribeEquipmentRequestV1Request', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBEEQUIPMENTREQUESTV1REQUEST,
  '__module__' : 'ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_equipment_request_api.v1.DescribeEquipmentRequestV1Request)
  })
_sym_db.RegisterMessage(DescribeEquipmentRequestV1Request)

DescribeEquipmentRequestV1Response = _reflection.GeneratedProtocolMessageType('DescribeEquipmentRequestV1Response', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBEEQUIPMENTREQUESTV1RESPONSE,
  '__module__' : 'ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_equipment_request_api.v1.DescribeEquipmentRequestV1Response)
  })
_sym_db.RegisterMessage(DescribeEquipmentRequestV1Response)

_BSSEQUIPMENTREQUESTAPISERVICE = DESCRIPTOR.services_by_name['BssEquipmentRequestApiService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Zcgithub.com/ozonmp/bss-equipment-request-api/pkg/bss-equipment-request-api;bss_equipment_request_api'
  _DESCRIBEEQUIPMENTREQUESTV1REQUEST.fields_by_name['id']._options = None
  _DESCRIBEEQUIPMENTREQUESTV1REQUEST.fields_by_name['id']._serialized_options = b'\372B\0042\002 \000'
  _BSSEQUIPMENTREQUESTAPISERVICE.methods_by_name['DescribeEquipmentRequestV1']._options = None
  _BSSEQUIPMENTREQUESTAPISERVICE.methods_by_name['DescribeEquipmentRequestV1']._serialized_options = b'\202\323\344\223\002 \"\033/v1/equipment_requests/{id}:\001*'
  _EQUIPMENTREQUEST._serialized_start=197
  _EQUIPMENTREQUEST._serialized_end=467
  _DESCRIBEEQUIPMENTREQUESTV1REQUEST._serialized_start=469
  _DESCRIBEEQUIPMENTREQUESTV1REQUEST._serialized_end=529
  _DESCRIBEEQUIPMENTREQUESTV1RESPONSE._serialized_start=531
  _DESCRIBEEQUIPMENTREQUESTV1RESPONSE._serialized_end=646
  _BSSEQUIPMENTREQUESTAPISERVICE._serialized_start=649
  _BSSEQUIPMENTREQUESTAPISERVICE._serialized_end=896
# @@protoc_insertion_point(module_scope)
