# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/bss_equipment_request_api/v1/bss_equipment_request_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2


class BssEquipmentRequestApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DescribeEquipmentRequestV1(self, stream: 'grpclib.server.Stream[ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2.DescribeEquipmentRequestV1Request, ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2.DescribeEquipmentRequestV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.bss_equipment_request_api.v1.BssEquipmentRequestApiService/DescribeEquipmentRequestV1': grpclib.const.Handler(
                self.DescribeEquipmentRequestV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2.DescribeEquipmentRequestV1Request,
                ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2.DescribeEquipmentRequestV1Response,
            ),
        }


class BssEquipmentRequestApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DescribeEquipmentRequestV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.bss_equipment_request_api.v1.BssEquipmentRequestApiService/DescribeEquipmentRequestV1',
            ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2.DescribeEquipmentRequestV1Request,
            ozonmp.bss_equipment_request_api.v1.bss_equipment_request_api_pb2.DescribeEquipmentRequestV1Response,
        )
